-- Criar tabela de histórico de pagamentos
CREATE TABLE public.SAAS_Pagamentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid NOT NULL,
  plano_id bigint,
  valor numeric NOT NULL,
  valor_original numeric,
  desconto_aplicado numeric DEFAULT 0,
  status text DEFAULT 'pending',
  gateway text DEFAULT 'asaas',
  gateway_payment_id text,
  gateway_customer_id text,
  tipo text DEFAULT 'renovacao',
  descricao text,
  pago_em timestamp with time zone
);

-- Enable RLS
ALTER TABLE public.SAAS_Pagamentos ENABLE ROW LEVEL SECURITY;

-- Policy for service role
CREATE POLICY "service_role_full_access_pagamentos" 
ON public.SAAS_Pagamentos 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- Index for faster queries
CREATE INDEX idx_pagamentos_user_id ON public.SAAS_Pagamentos(user_id);
CREATE INDEX idx_pagamentos_status ON public.SAAS_Pagamentos(status);
CREATE INDEX idx_pagamentos_created_at ON public.SAAS_Pagamentos(created_at DESC);