-- Criar tabela para colunas do CRM
CREATE TABLE public."SAAS_CRM_Colunas" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idUsuario" uuid NOT NULL,
  nome text NOT NULL,
  cor text NOT NULL DEFAULT 'bg-blue-500',
  ordem integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Criar tabela para leads do CRM
CREATE TABLE public."SAAS_CRM_Leads" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idUsuario" uuid NOT NULL,
  "idColuna" bigint NOT NULL REFERENCES public."SAAS_CRM_Colunas"(id) ON DELETE CASCADE,
  nome text,
  telefone text,
  mensagem text,
  valor numeric DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

-- Habilitar RLS
ALTER TABLE public."SAAS_CRM_Colunas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SAAS_CRM_Leads" ENABLE ROW LEVEL SECURITY;

-- Políticas para colunas
CREATE POLICY "Usuarios podem ver suas colunas" ON public."SAAS_CRM_Colunas"
  FOR SELECT USING ("idUsuario" = auth.uid());

CREATE POLICY "Usuarios podem criar suas colunas" ON public."SAAS_CRM_Colunas"
  FOR INSERT WITH CHECK ("idUsuario" = auth.uid());

CREATE POLICY "Usuarios podem atualizar suas colunas" ON public."SAAS_CRM_Colunas"
  FOR UPDATE USING ("idUsuario" = auth.uid());

CREATE POLICY "Usuarios podem deletar suas colunas" ON public."SAAS_CRM_Colunas"
  FOR DELETE USING ("idUsuario" = auth.uid());

-- Políticas para leads
CREATE POLICY "Usuarios podem ver seus leads" ON public."SAAS_CRM_Leads"
  FOR SELECT USING ("idUsuario" = auth.uid());

CREATE POLICY "Usuarios podem criar seus leads" ON public."SAAS_CRM_Leads"
  FOR INSERT WITH CHECK ("idUsuario" = auth.uid());

CREATE POLICY "Usuarios podem atualizar seus leads" ON public."SAAS_CRM_Leads"
  FOR UPDATE USING ("idUsuario" = auth.uid());

CREATE POLICY "Usuarios podem deletar seus leads" ON public."SAAS_CRM_Leads"
  FOR DELETE USING ("idUsuario" = auth.uid());

-- Política para service role (edge functions)
CREATE POLICY "service_role_full_access_colunas" ON public."SAAS_CRM_Colunas"
  FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "service_role_full_access_leads" ON public."SAAS_CRM_Leads"
  FOR ALL USING (true) WITH CHECK (true);

-- Índices
CREATE INDEX idx_crm_colunas_usuario ON public."SAAS_CRM_Colunas"("idUsuario");
CREATE INDEX idx_crm_leads_usuario ON public."SAAS_CRM_Leads"("idUsuario");
CREATE INDEX idx_crm_leads_coluna ON public."SAAS_CRM_Leads"("idColuna");
CREATE INDEX idx_crm_leads_telefone ON public."SAAS_CRM_Leads"(telefone);

-- Trigger para atualizar updated_at
CREATE OR REPLACE FUNCTION public.update_crm_lead_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_crm_leads_updated_at
  BEFORE UPDATE ON public."SAAS_CRM_Leads"
  FOR EACH ROW
  EXECUTE FUNCTION public.update_crm_lead_updated_at();