-- Tabela para armazenar etiquetas de conversas capturadas via webhook
CREATE TABLE public."SAAS_Chat_Labels" (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  "idUsuario" uuid NOT NULL,
  "idConexao" bigint NOT NULL,
  "instanceName" text NOT NULL,
  "remoteJid" text NOT NULL,
  "labelId" text NOT NULL,
  "labelName" text,
  "labelColor" text,
  "chatName" text,
  UNIQUE("idConexao", "remoteJid", "labelId")
);

-- Índices para busca rápida
CREATE INDEX idx_chat_labels_usuario ON public."SAAS_Chat_Labels" ("idUsuario");
CREATE INDEX idx_chat_labels_conexao ON public."SAAS_Chat_Labels" ("idConexao");
CREATE INDEX idx_chat_labels_label ON public."SAAS_Chat_Labels" ("labelId");
CREATE INDEX idx_chat_labels_remote ON public."SAAS_Chat_Labels" ("remoteJid");

-- RLS
ALTER TABLE public."SAAS_Chat_Labels" ENABLE ROW LEVEL SECURITY;

-- Policy para service_role
CREATE POLICY "service_role_full_access_chat_labels" 
ON public."SAAS_Chat_Labels" 
FOR ALL 
TO service_role
USING (true) 
WITH CHECK (true);